### PR TITLE
Bump Kubernetes to v1.28.0-alpha.4

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
Getting the latest CRI-API changes into `master`.
#### Which issue(s) this PR fixes:

None
#### Special notes for your reviewer:
Should merge after https://github.com/kubernetes-sigs/cri-tools/pull/1208

/hold
#### Does this PR introduce a user-facing change?

```release-note
Added support for `UserSpecifiedImage` CRI field on container creation RPC.
```

### CODE REVIEW

**Comment by feiskyer** [comment]
it's better to cut a new release before this?

**Comment by saschagrunert** [comment]
> it's better to cut a new release before this?

Yes, here we go: https://github.com/kubernetes-sigs/cri-tools/releases/tag/v1.27.1

**Comment by saschagrunert** [comment]
@kubernetes-sigs/cri-tools-maintainers PTAL

**Comment by saschagrunert** [comment]
@kubernetes-sigs/cri-tools-maintainers  PTAL

**Pull request merged**
