### PR TITLE
.github/workflows: add go mod and build cache

### PR DESCRIPTION
**Pull request by kolyshkin**
#### What type of PR is this?

/kind feature

_(can we have kind ci please?)_

#### What this PR does / why we need it:

Adds caching of go mod and go build, to presumably speed up github actions.

#### Which issue(s) this PR fixes:

None

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

### CODE REVIEW

**Comment by kolyshkin** [comment]
close/reopen to re-trigger CI

**Comment by feiskyer** [comment]
interesting. @kolyshkin have you checked how much time would it help to reduce?

**Comment by kolyshkin** [comment]
Hmm, I missed the fact that this repo uses vendor. In this case having go mod cache makes less sense.

Or perhaps we can drop vendor.

**Comment by kolyshkin** [comment]
> have you checked how much time would it help to reduce?

I will do some measurements later this week. I think the impact could be bigger without vendor/

**Comment by kolyshkin** [comment]
Let's close and open to re-run ci. Now we do have cache more or less populated and it might show.

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Pull request merged**
