### PR TITLE
Add documentation about 'statsp' command

### PR DESCRIPTION
**Pull request by kenneth-dsouza**
#### What type of PR is this?
/kind documentation

#### What this PR does / why we need it:
Add documentation about 'statsp' command.

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes-sigs/cri-tools/issues/953

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
@kenneth-dsouza may I ask you to sign the EasyCLA?

**Comment by kenneth-dsouza** [comment]
@saschagrunert  I signed the EasyCLA but for some reason it is not reflecting, let me check again.

**Review by saschagrunert — APPROVED** [review]
/lgtm

Thank yous @kenneth-dsouza!

**Pull request merged**
