### PR TITLE
Skip running portforward on host network test for non-linux

### PR DESCRIPTION
**Pull request by liyanhui1228**

### CODE REVIEW

**Comment by Random-Liu** [comment]
/lgtm

Windows container doesn't support host network, we should not run host network test on windows.

**Comment by liyanhui1228** [comment]
Looks like the test failures are not related to this change, can we skip it?

**Comment by Random-Liu** [comment]
/cc @saschagrunert crictl test is failing.

@liyanhui1228 Let's comment out the test from .travis.

**Comment by Random-Liu** [comment]
@liyanhui1228 My change is merged. Rebase your change, and the test should be skipped.

**Comment by liyanhui1228** [comment]
Needs lgtm label reapplied, thanks!

**Pull request merged**
