### PR TITLE
Add MacOS to the release platforms

### PR DESCRIPTION
**Pull request by dims**
Looks like we are missing `darwin/amd64`

Change-Id: I788b4d0c88dc4d9d07de4ac09c90d3a08220ed7c

### CODE REVIEW

**Comment by feiskyer** [comment]
> Looks like we are missing darwin/amd64

@dims Do you know any darwin container runtime?

**Comment by dims** [comment]
@feiskyer, couldn't we do port-forward etc to connect to a runtime? :)

**Comment by feiskyer** [comment]
@dims Usually couldn't. The runtimes on Linux are listening to an unix socket, so it's not possible to connect outside.

**Comment by dims** [comment]
interesting, thanks @feiskyer, i'll experiment a bit and may be reopen this another time.

**Comment by kad** [comment]
`
kad@kad:~> ssh -L /tmp/cr1.sock:/var/run/crio/crio.sock root@r720-1
`
and on another 
`
kad@kad:~> crictl -r /tmp/cr1.sock ps
W0327 15:28:16.354104    1065 util_unix.go:75] Using "/tmp/cr1.sock" as endpoint is deprecated, please consider using full url format "unix:///tmp/cr1.sock".
CONTAINER ID        IMAGE                                                              CREATED             STATE               NAME                      ATTEMPT
75f828c738641       f59dcacceff45b5474d1385cd5f500d0c019ed9ca50ed5b814ac0c5fcec8699e   4 days ago          CONTAINER_RUNNING   coredns                   0
....
`

**Comment by dims** [comment]
So i was right! :)

**Pull request closed without merging**
