### PR TITLE
Fix latest version in README.md

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:
Updating the version to match the latest release.
#### Which issue(s) this PR fixes:

None
#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by saschagrunert** [comment]
@kubernetes-sigs/cri-tools-maintainers PTAL

**Comment by saschagrunert** [comment]
@kubernetes-sigs/cri-tools-maintainers PTAL

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm

**Pull request merged**
