### PR TITLE
Drop support for docker log format

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
Dockershim has been removed from Kubernetes so we only need to support the CRI log format.

#### Which issue(s) this PR fixes:

None
#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
Removed support for docker log format in tests since dockershim is not available in Kubernetes any more.
```

### CODE REVIEW

**Comment by SergeyKanzhelev** [comment]
Sorry for the late comment. Will this work with CRI-DOCKERD? We are not dropping this from kubelet because of cri-dockerd to protect back compat.

**Comment by SergeyKanzhelev** [comment]
Do you know any maintainers of cri-dockerd? @nwneisen I see you are making releases. please advice

**Comment by nwneisen** [comment]
@SergeyKanzhelev I recently took over cri-dockerd. The project uses `k8s.io/klog/v2` which looks like the output can be configured. The logs I've seen have been in the logfmt format

**Comment by haircommander** [comment]
@nwneisen in this case we're talking about container logs--how does cri-dockerd write logs to disk for the kubelet to read them?

**Comment by nwneisen** [comment]
```
{"log":"I0719 22:04:51.982483       1 log.go:195] Started HTTP server on port 8080\n","stream":"stderr","time":"2023-07-19T22:04:51.993532538Z"}
{"log":"I0719 22:04:51.982923       1 log.go:195] Started UDP server on port  8081\n","stream":"stderr","time":"2023-07-19T22:04:51.993575341Z"}
{"log":"I0719 22:05:48.595826       1 log.go:195] GET /\n","stream":"stderr","time":"2023-07-19T22:05:48.595996805Z"}
{"log":"I0719 22:05:48.618534       1 log.go:195] GET /\n","stream":"stderr","time":"2023-07-19T22:05:48.618656559Z"}
```

Container logs are being written to disk in json format. I agree that `cri-dockerd` should use cri format. I will work on making a change for this.

**Comment by saschagrunert** [comment]
Thank you @nwneisen! :pray:

**Pull request merged**
