### PR TITLE
Update GitHub actions to go 1.16 and remove .travis.yml

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
We do not need the travis config any more since we switched to GitHub
actions. There we updated to the latest golang release.

#### Which issue(s) this PR fixes:

None
#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
@mikebrow it looks like that containerd v1.4.3 does not build with go 1.16. Is there a fix for this planned?

**Comment by mikebrow** [comment]
> @mikebrow it looks like that containerd v1.4.3 does not build with go 1.16. Is there a fix for this planned?

hey... we just moved up to 1.15.8 https://github.com/containerd/containerd/pull/5010

and there's an issue on 1.16 changing go get behavior https://github.com/containerd/containerd/pull/5009

**Review by mikebrow — APPROVED** [review]
LGTM following resolution of issues on https://github.com/containerd/containerd/pull/5005

**Comment by saschagrunert** [comment]
@feiskyer PTAL

**Review by feiskyer — APPROVED** [review]
/lgtm

**Pull request merged**
