### PR TITLE
Add CRI-O critest GitHub action

### PR DESCRIPTION
**Pull request by saschagrunert**
This adds an additional job for testing the latest CRI-O artifact
against the critest master.

Refers to #613

### CODE REVIEW

**Comment by saschagrunert** [comment]
Ready for review.

**Comment by mrunalp** [comment]
LGTM

**Comment by feiskyer** [comment]
This is cool, so we have both containerd and cri-o in github actions now

**Comment by feiskyer** [comment]
@saschagrunert do you know why github actions show the following failure annotation?

image

**Comment by saschagrunert** [comment]
> @saschagrunert do you know why github actions show the following failure annotation?
> 
> image

Yeah I'll try to fix it in https://github.com/kubernetes-sigs/cri-tools/pull/621 too :)

**Pull request merged**
