### PR TITLE
add swap column to crictl stats

### PR DESCRIPTION
**Pull request by kannon92**
#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
Add Swap to `crictl stats` display.
#### Does this PR introduce a user-facing change?

```release-note
Add swap to crictl stats default output.
```

### CODE REVIEW

**Comment by kannon92** [comment]
/hold

Going to test.

**Review by SergeyKanzhelev — COMMENTED** [review]
/lgtm

It will be `0` most times unless somebody enabled it. So it is good to have it as a last column.

**Comment by kannon92** [comment]
> great. I was wondering how it will behave when there is no swap. It should panic or anything

We always show swap in the stats (crictl stats -output=json) will show that it is 0.

From what I saw it was reporting zero.

**Review by saschagrunert — APPROVED** [review]

**Review by feiskyer — COMMENTED** [review]
let's get this in

/hold cancel

**Pull request merged**
