### PR TITLE
Update Windows images for ltsc2022

### PR DESCRIPTION
**Pull request by dcantah**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Makes it so critest can run on Windows ltsc2022

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by dcantah** [comment]
fyi @jsturtevant @marosset

**Comment by dcantah** [comment]
Will look at the CI failures in the morning.. seems like it can't install containerd for some reason.

**Review by saschagrunert — APPROVED** [review]

**Comment by dcantah** [comment]
Hmm, something must've changed in ctrd's makefile. To the depths I go!

**Comment by marosset** [comment]
changes LGTM

**Comment by dcantah** [comment]
Trying to see where the ctrd CI is going awry. Testing only on 1.5.2

**Comment by dcantah** [comment]
Aaaand looks like it worked haha

**Comment by dcantah** [comment]
Ok pushed a fix to containerd https://github.com/containerd/containerd/pull/6322.

**Comment by aznashwan** [comment]
FWIW I was able to independently validate this fixes the `critest` image errors on a 20348 VM (namely ones that look like [this](https://github.com/aznashwan/containerd/runs/4444853626?check_suite_focus=true))

Many thanks @dcantah!

**Comment by feiskyer** [comment]
@dcantah thanks for the fix. How could we get the fix merged?

**Comment by dcantah** [comment]
@feiskyer I was waiting for the ctrd make fix to get in so we can re-run the CI here. https://github.com/containerd/containerd/pull/6322 This looks close to landing

**Comment by dcantah** [comment]
Makefile change got in so re-running CI to see

**Comment by dcantah** [comment]
Ugh -_-. Ok, `make install` can find the containerd binaries again, but it looks like for some reason it's plopping the shim in /bin instead of the relative path bin in the containerd repo where the rest of the binaries are. Why this is, I'm not sure yet

**Review by feiskyer — COMMENTED** [review]
/lgtm

**Comment by feiskyer** [comment]
merging manually because dockershim failures are not related.

**Pull request merged**
