### PR TITLE
fix error way of parsing URL for cmd exec and attach

### PR DESCRIPTION
**Pull request by tanyifeng**
Parsing URL with url.schema other than prefix of URL.

Signed-off-by: t00416110 <tanyifeng1@huawei.com>

### CODE REVIEW

**Comment by tanyifeng** [comment]
> CLA

CLA check

**Comment by tanyifeng** [comment]
> Thanks for your pull request. Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).
> 
>  **Please follow instructions at https://git.k8s.io/community/CLA.md#the-contributor-license-agreement to sign the CLA.**
> 
> It may take a couple minutes for the CLA signature to be fully registered; after that, please reply here with a new comment and we'll verify. Thanks.
> 
> * If you've already signed a CLA, it's possible we don't have your GitHub username or you're using a different email address.  Check your existing CLA data and verify that your [email is set on your git commits](https://help.github.com/articles/setting-your-email-in-git/).
> * If you signed the CLA as a corporation, please sign in with your organization's credentials at https://identity.linuxfoundation.org/projects/cncf to be authorized.
> * If you have done the above and are still having issues with the CLA being reported as unsigned, please email the CNCF helpdesk: [helpdesk@rt.linuxfoundation.org](mailto:helpdesk@rt.linuxfoundation.org)

Singed

**Comment by tanyifeng** [comment]
The Travis CI failed due to go version in build machine is lower than go1.11.1

**Comment by feiskyer** [comment]
> The Travis CI failed due to go version in build machine is lower than go1.11.1

Yep, k/k requires go 1.11.1 now. Let me update Go version first.

**Comment by feiskyer** [comment]
Re-trigger travis testing...

**Comment by tanyifeng** [comment]
> gofmt check failed. @tanyifeng Could you fix gofmt issues?

Done

**Pull request merged**
