### PR TITLE
WIP: Update seccomp tests to use CRI security profile field

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:
The CRI validation for the security context now uses the seccomp field
instead of the deprecated seccomp profile path. This means that the
docker/default tests are now testing for `RuntimeDefault`. Invalid test
cases have been removed, too.

#### Which issue(s) this PR fixes:

Refers to #678 
#### Does this PR introduce a user-facing change?

```release-note
critest now uses the new security profile field instead of the seccomp profile path for validation testing
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
cc @mrunalp @mikebrow 

I expect the CI to fail here…

**Comment by mikebrow** [comment]
> cc @mrunalp @mikebrow
> 
> I expect the CI to fail here… As an alternative, we could also duplicate the tests to still preserve the old ones.

I think it makes sense to test both, yes.

**Pull request closed without merging**
