### PR TITLE
adds containerd github action tests

### PR DESCRIPTION
**Pull request by mikebrow**
Working with @hickeyma this is a carry from https://github.com/hickeyma/cri-tools/commit/10f3270919667ba27086830ca67351d8b4549461

Addressing the containerd portion of #613

Signed-off-by: Mike Brown <brownwm@us.ibm.com>

### CODE REVIEW

**Comment by mikebrow** [comment]
Still needs some work to get it force the containerd/cri install.deps to use "this" pr aka github.sha... "fatal: reference is not a tree:  20b5d374241871ee510119bf3fef211777859fdd"

And we need to enable github actions didn't run here for some reason.

**Comment by mikebrow** [comment]
Ok looks good to go for review..

**Comment by saschagrunert** [comment]
Do we have to merge it before it even runs?

The settings show that it’s enabled:
C0E3E44B-5BBF-4A82-9598-489333E264B8

**Comment by mikebrow** [comment]
Didn't have to before in other repos.. it just worked.

**Comment by mikebrow** [comment]
I'll push a nop change. You can see the success in the branch on my fork.

**Comment by mikebrow** [comment]
Whooot it's running :-)

**Comment by mikebrow** [comment]
we can add a matrix of platforms and versions of containerd in a follow up...

This PR adds the CI test for the PR commit of this repo running on ubuntu-18.04 LTS using  containerd master + containerd cri master and their dependencies (runc etal).

**Comment by hickeyma** [comment]
Nice way to return from leave. Great work @mikebrow. Thanks for getting this over the line.

**Pull request merged**
