### PR TITLE
add tests for remove container by force rule

### PR DESCRIPTION
**Pull request by mikebrow**
Testing RemoveContainer API to address issue #632

Signed-off-by: Mike Brown <brownwm@us.ibm.com>

### CODE REVIEW

**Comment by mikebrow** [comment]
@hickeyma heads up.. I expected a fail for containerd and possibly dockershim here .. but containerd passed. I may not have the testcase right yet, or my assumption of fail may have been wrong. However, I checked out the logs and it seems this PR's change is only being tested on cri-o not containerd. So there's a logic bug in the actions test for containerd somewhere, such that containerd is running on a different version of critest than it should be. Not sure if this is a regression.. I thought we checked the version tag that was being run for containerd. Maybe we should be outputting the build tag in the critest output if possible.

cri-o:
```
[It] runtime should support removing created container [Conformance]
```
containerd:
```
[It] runtime should support removing container [Conformance]
```

**Comment by hickeyma** [comment]
> I expected a fail for containerd and possibly dockershim here .. but containerd passed.

@mikebrow Not sure why this isn't tested on containerd. It calls `make test-cri` in https://github.com/kubernetes-sigs/cri-tools/blob/master/.github/workflows/containerd.yml#L107 which calls the target in https://github.com/containerd/cri/blob/master/hack/test-cri.sh. Looking at this, it does not skip any of the tests.

Re dockershim, it does skip some tests as follows: https://github.com/kubernetes-sigs/cri-tools/blob/master/hack/run-critest.sh#L43

**Comment by mikebrow** [comment]
> > I expected a fail for containerd and possibly dockershim here .. but containerd passed.
> 
> @mikebrow Not sure why this isn't tested on containerd. It calls `make test-cri` in https://github.com/kubernetes-sigs/cri-tools/blob/master/.github/workflows/containerd.yml#L107 which calls the target in https://github.com/containerd/cri/blob/master/hack/test-cri.sh. Looking at this, it does not skip any of the tests.
> 
> Re dockershim, it does skip some tests as follows: https://github.com/kubernetes-sigs/cri-tools/blob/master/hack/run-critest.sh#L43

yeah it's not a skip issue.. for containerd it's not testing on the PR itself.. could be on the parent commit not sure..

**Comment by hickeyma** [comment]
LGTM NB

**Pull request merged**
