### PR TITLE
fix log info for mount test case

### PR DESCRIPTION
**Pull request by sayaoailun**
Signed-off-by: sayaoailun <guojianwei007@126.com>

#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:

fix wrong log info for mount test case

#### Which issue(s) this PR fixes:

None

#### Does this PR introduce a user-facing change?

NONE

```release-note

```

### CODE REVIEW

**Review by feiskyer — COMMENTED** [review]
Thanks for the fix
/lgtm
/approve

**Review by saschagrunert — APPROVED** [review]

**Pull request merged**
