### PR TITLE
Search program directory for config as fallback

### PR DESCRIPTION
**Pull request by jterry75**
Causes crictl to search its own directory for crictl.yaml if the user
does not specify a config path, and the default global path does not
exist.

Signed-off-by: Kevin Parsons <kevpar@microsoft.com>
Signed-off-by: Justin Terry (VM) <juterry@microsoft.com>

### CODE REVIEW

**Comment by jterry75** [comment]
@kevpar - FYI

**Comment by jterry75** [comment]
@feiskyer - PTAL when you get a chance.

**Comment by feiskyer** [comment]
lgtm. @kevpar Could you sign the CLA?

**Comment by jterry75** [comment]
@yujuhong - I was carrying this for @kevpar to avoid CLA since I am already a member and the commit has signoff by me as well. Does he have to sign the CLA as well?

**Comment by feiskyer** [comment]
the commit is from him, so I think it's still required to pass the CLA check.

**Comment by kevpar** [comment]
I have signed the CLA.

**Comment by jterry75** [comment]
Thanks!

**Pull request merged**
