### PR TITLE
Do not auto find runtime handler for user namespaces tests

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
We rely on the test context runtime handler, which can be empty (`""`) for the default one reported by the runtime.

#### Which issue(s) this PR fixes:

None
#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
@kubernetes-sigs/cri-tools-maintainers PTAL

**Comment by saschagrunert** [comment]
@kubernetes-sigs/cri-tools-maintainers PTAL

**Comment by kwilczynski** [comment]
> @kubernetes-sigs/cri-tools-maintainers PTAL

@saschagrunert, looks good to me!

Even though I have no approval powers here.

**Comment by saschagrunert** [comment]
@kubernetes-sigs/cri-tools-maintainers PTAL

**Pull request merged**
