### PR TITLE
Update critest from 1.17 to 1.27 in the documentation

### PR DESCRIPTION
**Pull request by afbjorklund**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

The version and architecture was outdated and hardcoded.

#### Which issue(s) this PR fixes:

None

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]
Thank you!

**Review by adisky — COMMENTED** [review]
/lgtm

**Comment by saschagrunert** [comment]
Just a docs update, merging.

**Pull request merged**
