### PR TITLE
Add validation when container OOMKilled

### LINKED ISSUE #1102: critest: add a test to validate the reason message returned for cgroup OOM-killed container
#### What would you like to be added:

Similar to e2e test in k8s (https://github.com/kubernetes/kubernetes/pull/113205), it may be a good idea to implement similar test in critest. So runtimes will keep the reason message consistent for this case.

#### Why is this needed:

To validate the behavior.

/cc @mikebrow 

/good-first-issue
/help-wanted

### PR DESCRIPTION
**Pull request by bitoku**
#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
This PR adds validation for OOMKilled container.

It checks if exitCode==137 && reason==OOMKilled

#### Which issue(s) this PR fixes:

Fixes #1102

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by haircommander** [comment]
thanks @bitoku is this still a draft?

**Comment by bitoku** [comment]
I wanted to check the result of the tests before making it not-draft.
I thought some tests would be run when I created a PR.

I think I have to check the behaviour on my machine.

**Comment by SergeyKanzhelev** [comment]
related to #1102?

**Comment by bitoku** [comment]
Yes, sorry I put `Fixes` in a comment section.
I changed it.

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm

**Review by saschagrunert — CHANGES_REQUESTED** [review]
CI fails because of this change:

```
  [FAILED] in [It] - github.com/kubernetes-sigs/cri-tools/pkg/validate/container_linux.go:202 @ 05/02/23 07:12:14.529
  STEP: stop PodSandbox @ 05/02/23 07:12:14.529
  STEP: delete PodSandbox @ 05/02/23 07:12:14.692
  << Timeline

  [FAILED] Timed out after 60.000s.
  Expected
      <v1.ContainerState>: 1
  to equal
      <v1.ContainerState>: 2
  In [It] at: github.com/kubernetes-sigs/cri-tools/pkg/validate/container_linux.go:202 @ 05/02/23 07:12:14.529
------------------------------

Summarizing 1 Failure:
  [FAIL] [k8s.io] Container OOM runtime should output OOMKilled reason [It] should terminate with exitCode 137 and reason OOMKilled
  github.com/kubernetes-sigs/cri-tools/pkg/validate/container_linux.go:202

Ran 84 of 89 Specs in 85.944 seconds
```

**Comment by bitoku** [comment]
I added `MemorySwapLimitInBytes` to make containerd 1.6.12 kill the container

**Comment by bitoku** [comment]
It seems it timed out in the build step.
In my forked repo it worked fine. https://github.com/bitoku/cri-tools/actions/runs/4874757908/jobs/8738852586
what should I do to avoid this?

**Comment by SergeyKanzhelev** [comment]
> It seems it timed out in the build step. In my forked repo it worked fine. https://github.com/bitoku/cri-tools/actions/runs/4874757908/jobs/8738852586 what should I do to avoid this?

Looking at output

```
/home/runner/work/cri-tools/cri-tools/src/github.com/kubernetes-sigs/cri-tools/_output/bin/amd64-linux/critest: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=6hH4QIaLpEAi2pPTkXjM/p7rAmmQsKcwXNiSq71Pp/v2qCePMxS8o3LJbNl6vV/DLEqVztH4GdjjQQsnEhh, with debug_info, not stripped
/home/runner/work/cri-tools/cri-tools/src/github.com/kubernetes-sigs/cri-tools/_output/bin/386-linux/critest: ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), statically linked, Go BuildID=8x_9goimsDpvOjYczyGi/TGXIQnu_fsndIJfvAp_3/pTfR-ku9DMEExIlFvF-2/5DzwE1wj07zx3aaWnDlH, with debug_info, not stripped
/home/runner/work/cri-tools/cri-tools/src/github.com/kubernetes-sigs/cri-tools/_output/bin/arm-linux/critest: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), statically linked, Go BuildID=heqh_XiGFuGUUGyV7ajT/gIItSLVm05wWG-9wzJf1/PE884KcLqSm2IECGu6Yy/gbtPFxCeIcGu6SCATIQI, with debug_info, not stripped
/home/runner/work/cri-tools/cri-tools/src/github.com/kubernetes-sigs/cri-tools/_output/bin/arm64-linux/critest: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, Go BuildID=3L_RUvc9CV4LBKdr1LNw/h_3YbKa4dy5amkTPxEgi/YxfWRACuvXTrVaMx3yld/3otM0klQQoX-wq39Qr8y, with debug_info, not stripped
Error: The operation was canceled.
``` 

and based on the ordering the `windows/amd64` test fails. Does it pass OK for you? Do you use 1.6.2 on your local environment?

**Comment by bitoku** [comment]
Yes It passes OK on github actions in my forked repo.
I didn't run it on my local.

> Do you use 1.6.2 on your local environment?

Are you mentioning about containerd version?
I don't think containerd version has to do with the `build` action because it's not dependent on containerd.

I looked over the past commits and some commits failed `build` action due to timed out.
https://github.com/kubernetes-sigs/cri-tools/commit/471c53d49fec6054cf3b7d165fbeb687c58b2036
https://github.com/kubernetes-sigs/cri-tools/commit/8d781b8f172a777c4e9781c278bd0572b3960235
https://github.com/kubernetes-sigs/cri-tools/commit/73472f1555fd0edb473fa9bde6432dd025fd3ab8

Do we need to set build timeout 20 mins?
Can we relax the timeout-minutes?

**Comment by SergeyKanzhelev** [comment]
> Do we need to set build timeout 20 mins?

Sounds reasonable for me. @saschagrunert?

**Comment by saschagrunert** [comment]
Yeah let’s increase the timeout. This test flakes often because of that.

**Review by saschagrunert — APPROVED** [review]

**Pull request merged**
