### PR TITLE
Bump golang to v1.22 in CI

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
Update the go version used in CI to the latest minor release.
#### Which issue(s) this PR fixes:

None
#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
Gave it a rebase.

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm
/approve

**Comment by mikebrow** [comment]
Reads like the windows pause container has a bad missing layer... `[FAILED] failed to create PodSandbox: rpc error: code = Unknown desc = failed to get sandbox image "registry.k8s.io/pause:3.8": failed to pull image "registry.k8s.io/pause:3.8": failed to pull and unpack image "registry.k8s.io/pause:3.8": failed to extract layer sha256:5ad177daa048ca8b354b9ad03deac863ff519a2860a35dc9fdc0011619aacc3c: SetFileInformationByHandle \\?\C:\Users\RUNNER~1\AppData\Local\Temp\hcs1803373873\Files.$wcidirs$: Invalid access to memory location.: unknown`

**Comment by cpuguy83** [comment]
Error looks like its due to compiling 1.6 and 1.7 with go1.22 with an outdated go-winio.
See:
- https://github.com/golang/go/issues/65069
- https://github.com/moby/moby/pull/47743

**Comment by mikebrow** [comment]
@saschagrunert could you re-run these testbuckets, microsoft team believes they have fixed 1.7 5days back right here https://github.com/containerd/containerd/pull/10232 and are working on 1.6 update for the golang changes.

**Comment by mikebrow** [comment]
fixes have been merged .. these containerd buckets should pass pls restart.

**Comment by cpuguy83** [comment]
Can someone re-trigger the tests?
I believe the failures should work without needing to change anything here.

**Comment by saschagrunert** [comment]
I assume we're good since other PR's CI passes now.

**Pull request merged**
