### PR TITLE
Cleanup deprecations 

### PR DESCRIPTION
**Pull request by surik**
#### What type of PR is this?

/kind cleanup
/kind deprecation

#### What this PR does / why we need it:

- `io/ioutil` has been deprecated since Go 1.19.
- `rand.Seed` has been deprecated since Go 1.20
- `strings.Title` has been deprecated since Go 1.18
- `executor.Stream` is deprecated: use `StreamWithContext` instead (https://github.com/kubernetes/kubernetes/pull/103177)
- `urfave's cli.NewExitError` is deprecated. This function is a duplicate of `Exit` and will eventually be removed.

#### Which issue(s) this PR fixes:

None

#### Special notes for your reviewer:

I addressed each issue in its own commit so should be easier to review one by one. I'm happy to squash everything if needed.

I had to exclude some checks for `SA1019` as the proposed alternative doesn't look compatible with the protobuf in cri-api.

```
cmd/crictl/util.go:34:2: SA1019: "github.com/golang/protobuf/jsonpb" is deprecated: Use the "google.golang.org/protobuf/encoding/protojson" package instead. (staticcheck)
        "github.com/golang/protobuf/jsonpb"
        ^
cmd/crictl/util.go:35:2: SA1019: "github.com/golang/protobuf/proto" is deprecated: Use the "google.golang.org/protobuf/proto" package instead. (staticcheck)
        "github.com/golang/protobuf/proto"
        ^
```

Also, I'm not sure that I went right direction addressing `strings.Title`.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Review by SergeyKanzhelev — COMMENTED** [review]
code changes lgtm

/lgtm

I am not sure why static checks were disabled before, @saschagrunert ok to enable it?

**Comment by SergeyKanzhelev** [comment]
/remove-kind deprecation

Deprecation kind is used to deprecate features. This is a cleanup

**Review by saschagrunert — COMMENTED** [review]
Thank you for the contribution @surik! Unfortunately CI is not happy about it. We could also give golangci-lint a version and config bump if you want.

**Comment by surik** [comment]
Hi @saschagrunert no need to bump `golangci-lint`. I had to run it locally on Linux before opening PR. I believe it should be fine now.

**Comment by saschagrunert** [comment]
@surik the streaming tests seems to fail, I bet it's related to the context.

**Comment by surik** [comment]
Honesty I do not fully understand what's wrong with the containerd tests. @saschagrunert let me know if you have any ideas.

**Comment by saschagrunert** [comment]
Ugh, those tests seem to be broken all over the place :thinking:

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm

**Comment by saschagrunert** [comment]
Please rebase to the the latest CI changes in.

**Comment by saschagrunert** [comment]
Lol, @k8s-ci-robot merged without giving GitHub actions a chance to retest :eyes:

**Pull request merged**
