### PR TITLE
Fix docker installation for CI

### PR DESCRIPTION
**Pull request by feiskyer**
Fix docker installation for CI and upgrade docker version to ~~18.06~~ 17.06.

Update: older version 17.06 is used because https://github.com/kubernetes-sigs/cri-tools/pull/445#issuecomment-472343719.

### CODE REVIEW

**Comment by Random-Liu** [comment]
There is a behavior change in the new docker.

For Docker 17.03, exec process inherits additional group id from the init process:
```
$ docker run --group-add 1234 busybox id -G
0 10 1234
lantaol@e2e-test-lantaol-minion-group-cq8p ~ $ docker run --group-add 1234 -d busybox sleep 1000
87e52362a4962267f408d6646c3de4482b5f6247de5362103c309bbeadccc175
lantaol@e2e-test-lantaol-minion-group-cq8p ~ $ docker exec 87 id -G
0 10 1234
```

For Docker 18.09, exec process doesn't inherit additional group id from the init process:
```
$ docker run --group-add 1234 busybox id -G
0 10 1234
$ docker run --group-add 1234 -d busybox sleep 1000
ded77fec7e0bc07542037ad4a669b7ffed3211d2762fc1d3381fa84af67f28c1
$ docker exec de id -G
0
```

I'm investigating why the change was made. Tell me if you have more information about this. :)

**Comment by Random-Liu** [comment]
OK. I think this is a docker bug introduced after switching to containerd 1.0.

Will file a docker issue and link here.

**Comment by Random-Liu** [comment]
See https://github.com/moby/moby/issues/38865

**Comment by feiskyer** [comment]
@Random-Liu Thanks for the tip, didn't notice this bug. Let me switch to 18.03 then.

**Comment by feiskyer** [comment]
weird, static binaries of 18.03 don't support seccomp now.

**Comment by feiskyer** [comment]
Dockershim panic now with errors:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x32e2d7f]
goroutine 3526 [running]:
k8s.io/kubernetes/pkg/kubelet/dockershim.(*dockerService).RemoveImage(0xc0006f1290, 0x48af4a0, 0xc002393b90, 0xc001b54c78, 0xc0006f1290, 0xc002393b00, 0x3a95260)
	/home/travis/gopath/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/dockershim/docker_image.go:134 +0x9f
k8s.io/kubernetes/pkg/kubelet/apis/cri/runtime/v1alpha2._ImageService_RemoveImage_Handler(0x42b7520, 0xc0006f1290, 0x48af4a0, 0xc002393b90, 0xc00016ebd0, 0x0, 0x0, 0x0, 0x22666669642f6239, 0x69446b726f57222c)
	/home/travis/gopath/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/apis/cri/runtime/v1alpha2/api.pb.go:4807 +0x23e
k8s.io/kubernetes/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc000228700, 0x48ce9a0, 0xc0022d6e00, 0xc0023d4d00, 0xc0005ea180, 0x76184a8, 0x0, 0x0, 0x0)
```

Filed https://github.com/kubernetes/kubernetes/pull/75367 to fix this issue.

**Comment by feiskyer** [comment]
Self applied lgtm since it also blocks other PRs.

**Pull request merged**
