### PR TITLE
Update critest Windows tests.

### PR DESCRIPTION
**Pull request by adelina-t**
Update images used. Given the size of the Windows container images,
pull times make these tests unresonable for CI work. There has been
a lot of work done around the test images for K8s E2E tests on Windows,
including creating small images based on Nanoserver and also creating
a image promoting process for automated build & publish of images.

This commit also changes a small command for a test that was not
correct for Windows.

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by feiskyer** [comment]
@hickeyma any idea why the containerd tests are failing?

**Comment by adelina-t** [comment]
> @hickeyma any idea why the containerd tests are failing?

They seem to be failing when cloning the containerd/containerd repo. Might be because the changed master -> main naming ?

**Comment by feiskyer** [comment]
containerd issue fixed in #788. let's re-run the tests

**Comment by feiskyer** [comment]
it is still running as master branch. @adelina-t could you try a rebase?

**Comment by adelina-t** [comment]
> it is still running as master branch. @adelina-t could you try a 

> it is still running as master branch. @adelina-t could you try a rebase?

I’ll do that ASAP, need to get n

**Review by feiskyer — COMMENTED** [review]
/lgtm
/approve

**Comment by hickeyma** [comment]
@feiskyer Only seeing it now as was on leave. Glad you got it resolved.

**Comment by hickeyma** [comment]
Nice improvements, thanks @adelina-t

**Pull request merged**
