### PR TITLE
Switch to golang native error wrapping

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

We now use the golang native error wrapping instead of the deprecated `github.com/pkg/errors` library.

#### Which issue(s) this PR fixes:

None

#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
> @feiskyer had to rebase this one

Again

**Comment by feiskyer** [comment]
There are still lots of critest errors. Are they related to this change?

**Comment by saschagrunert** [comment]
> There are still lots of critest errors. Are they related to this change?

Every PR seems to fail with the latest containerd main. Maybe @mikebrow could help us if it not magically resolves?

**Comment by mikebrow** [comment]
might be fixed now https://github.com/containerd/containerd/pull/7198..

**Comment by feiskyer** [comment]
seems not fixed yet, rerun still failed

**Comment by mikebrow** [comment]
hmm one error ... loopback

**Comment by saschagrunert** [comment]
@mikebrow @feiskyer that looks like a flake, I'll give it a retry.

**Review by feiskyer — APPROVED** [review]
/lgtm

**Pull request merged**
